# Generated by Django 5.2.12 on 2026-04-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('alignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsuggestion',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_suggestions', to='alignment.streampost'),
        ),
    ]
