# Generated by Django 5.2.12 on 2026-04-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsuggestion',
            name='related_section_key',
        ),
    ]
