# Generated by Django 5.2.12 on 2026-04-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_agentsuggestion_related_section_key'),
        ('specs', '0002_remove_assumption_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsuggestion',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_suggestions', to='specs.projectdocument'),
        ),
        migrations.AlterField(
            model_name='agentsuggestion',
            name='target_type',
            field=models.CharField(default='document', max_length=64),
        ),
    ]
