# Generated by Django 5.2.12 on 2026-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvite',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
