# Generated by Django 5.2.12 on 2026-04-08 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_repair_projectinvite_last_sent_at'),
        ('specs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='openai', max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('operation', models.CharField(choices=[('section_revision', 'Section Revision'), ('concern_scan', 'Concern Scan'), ('concern_reevaluation', 'Concern Re-Evaluation'), ('concern_proposal', 'Concern Proposal'), ('consistency_scan', 'Consistency Scan')], max_length=32)),
                ('response_id', models.CharField(blank=True, max_length=128)),
                ('response_status', models.CharField(blank=True, max_length=32)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('usage_details', models.JSONField(blank=True, default=dict)),
                ('context_metadata', models.JSONField(blank=True, default=dict)),
                ('concern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to='specs.projectconcern')),
                ('concern_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to='specs.concernrun')),
                ('consistency_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to='specs.consistencyrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='projects.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='specs_aiusa_project_2c4bc2_idx'), models.Index(fields=['organization', 'created_at'], name='specs_aiusa_organiz_fe6e15_idx'), models.Index(fields=['user', 'created_at'], name='specs_aiusa_user_id_e194ef_idx'), models.Index(fields=['operation', 'created_at'], name='specs_aiusa_operati_f93154_idx')],
            },
        ),
    ]
