# Generated by Django 5.2.12 on 2026-04-04 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_agentsuggestion_related_section_key'),
        ('alignment', '0002_remove_blocker_related_section_key_and_more'),
        ('projects', '0001_initial'),
        ('specs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assumption',
            name='section',
        ),
        migrations.AlterUniqueTogether(
            name='specversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='specversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specversion',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='specversion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='specversion',
            name='source_agent',
        ),
        migrations.RemoveField(
            model_name='specversion',
            name='source_assumption',
        ),
        migrations.RemoveField(
            model_name='specversion',
            name='source_decision',
        ),
        migrations.RemoveField(
            model_name='specversion',
            name='source_post',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='spec_version',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('project_revision_created', 'Project Revision Created'), ('document_created', 'Document Created'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('document_reordered', 'Document Reordered'), ('decision_approved', 'Decision Approved'), ('decision_rejected', 'Decision Rejected'), ('decision_implemented', 'Decision Implemented'), ('assumption_created', 'Assumption Created'), ('assumption_validated', 'Assumption Validated'), ('assumption_invalidated', 'Assumption Invalidated'), ('agent_applied', 'Agent Applied'), ('agent_dismissed', 'Agent Dismissed'), ('consistency_run_completed', 'Consistency Run Completed'), ('consistency_run_failed', 'Consistency Run Failed'), ('consistency_issue_resolved', 'Consistency Issue Resolved'), ('consistency_issue_dismissed', 'Consistency Issue Dismissed'), ('export_created', 'Export Created'), ('membership_changed', 'Membership Changed')], max_length=40),
        ),
        migrations.CreateModel(
            name='ConsistencyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='openai', max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-analyzed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsistencyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_issues', to='projects.project')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='specs.consistencyrun')),
            ],
            options={
                'ordering': ['-updated_at', '-detected_at'],
                'unique_together': {('project', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=96)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('overview', 'Overview'), ('goals', 'Goals'), ('requirements', 'Requirements'), ('ui-ux', 'UI/UX'), ('tech-stack', 'Tech Stack'), ('infra', 'Infra'), ('risks-open-questions', 'Risks & Open Questions'), ('custom', 'Custom')], default='custom', max_length=64)),
                ('source_kind', models.CharField(choices=[('preset', 'Preset'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aligned', 'Aligned'), ('iterating', 'Iterating'), ('blocked', 'Blocked')], default='iterating', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='assumption',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assumptions', to='specs.projectdocument'),
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_revisions', to=settings.AUTH_USER_MODEL)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_revisions', to='specs.projectrevision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.project')),
                ('source_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revisions', to='agents.agentsuggestion')),
                ('source_assumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revisions', to='specs.assumption')),
                ('source_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revisions', to='alignment.decision')),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revisions', to='alignment.streampost')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('project', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_revisions', to=settings.AUTH_USER_MODEL)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_revisions', to='specs.documentrevision')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='specs.projectdocument')),
                ('project_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions', to='specs.projectrevision')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('document', 'number')},
            },
        ),
        migrations.AddField(
            model_name='auditevent',
            name='project_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='specs.projectrevision'),
        ),
        migrations.DeleteModel(
            name='SpecSection',
        ),
        migrations.DeleteModel(
            name='SpecVersion',
        ),
    ]
