# Generated by Django 5.2.12 on 2026-04-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_aiusagerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagerecord',
            name='operation',
            field=models.CharField(choices=[('section_revision', 'Section Revision'), ('concern_scan', 'Concern Scan'), ('concern_reevaluation', 'Concern Re-Evaluation'), ('concern_proposal', 'Concern Proposal'), ('consistency_scan', 'Consistency Scan'), ('attachment_summary', 'Attachment Summary'), ('stream_spec_apply', 'Stream Spec Apply')], max_length=32),
        ),
    ]
