# Generated by Django 5.2.12 on 2026-04-05 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0003_blocker_related_document_decision_related_document_and_more'),
        ('projects', '0001_initial'),
        ('specs', '0003_seed_default_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('project_revision_created', 'Project Revision Created'), ('document_created', 'Document Created'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('document_reordered', 'Document Reordered'), ('decision_approved', 'Decision Approved'), ('decision_rejected', 'Decision Rejected'), ('decision_implemented', 'Decision Implemented'), ('assumption_created', 'Assumption Created'), ('assumption_validated', 'Assumption Validated'), ('assumption_invalidated', 'Assumption Invalidated'), ('agent_applied', 'Agent Applied'), ('agent_dismissed', 'Agent Dismissed'), ('concern_run_completed', 'Concern Run Completed'), ('concern_run_failed', 'Concern Run Failed'), ('concern_promoted', 'Concern Promoted'), ('concern_dismissed', 'Concern Dismissed'), ('concern_reevaluated', 'Concern Re-Evaluated'), ('concern_marked_stale', 'Concern Marked Stale'), ('concern_proposal_created', 'Concern Proposal Created'), ('concern_proposal_change_accepted', 'Concern Proposal Change Accepted'), ('concern_proposal_change_rejected', 'Concern Proposal Change Rejected'), ('consistency_run_completed', 'Consistency Run Completed'), ('consistency_run_failed', 'Consistency Run Failed'), ('consistency_issue_resolved', 'Consistency Issue Resolved'), ('consistency_issue_dismissed', 'Consistency Issue Dismissed'), ('export_created', 'Export Created'), ('membership_changed', 'Membership Changed')], max_length=40),
        ),
        migrations.CreateModel(
            name='ConcernRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='openai', max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('concern_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('trigger', models.CharField(default='manual', max_length=24)),
                ('target_concern_fingerprint', models.CharField(blank=True, max_length=128)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-analyzed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=128)),
                ('concern_type', models.CharField(choices=[('consistency', 'Consistency'), ('implementability', 'Implementability'), ('usability', 'Usability'), ('business_viability', 'Business Viability'), ('human_flag', 'Human Flag')], default='human_flag', max_length=32)),
                ('raised_by_kind', models.CharField(choices=[('ai', 'AI'), ('human', 'Human'), ('system', 'System')], default='system', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('stale', 'Stale'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('recommendation', models.TextField(blank=True)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('reevaluation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('last_reevaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_concerns', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_concerns', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='concerns', to='specs.projectdocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_concerns', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerns', to='specs.concernrun')),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_concerns', to='alignment.streampost')),
            ],
            options={
                'ordering': ['-updated_at', '-detected_at'],
                'unique_together': {('project', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='ConcernProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='openai', max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_applied', 'Partially Applied'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='open', max_length=24)),
                ('created_by_kind', models.CharField(choices=[('ai', 'AI'), ('human', 'Human'), ('system', 'System')], default='ai', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_proposals', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_concern_proposals', to=settings.AUTH_USER_MODEL)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='specs.projectconcern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConcernProposalChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('original_body', models.TextField(blank=True)),
                ('proposed_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_concern_proposal_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_proposal_changes', to='specs.projectdocument')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='specs.concernproposal')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('proposal', 'document')},
            },
        ),
    ]
