# Generated by Django 5.2.12 on 2026-04-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alignment', '0001_initial'),
        ('projects', '0001_initial'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampost',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='specs.projectconcern'),
        ),
        migrations.AddField(
            model_name='streampost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_posts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='alignment.streampost'),
        ),
        migrations.AddField(
            model_name='decision',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='alignment.streampost'),
        ),
        migrations.AddField(
            model_name='blocker',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockers', to='alignment.streampost'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionapproval',
            unique_together={('decision', 'approver')},
        ),
    ]
