# Generated by Django 5.2.12 on 2026-04-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0002_remove_blocker_related_section_key_and_more'),
        ('specs', '0002_remove_assumption_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocker',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockers', to='specs.projectdocument'),
        ),
        migrations.AddField(
            model_name='decision',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='specs.projectdocument'),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='specs.projectdocument'),
        ),
    ]
