# Generated by Django 5.2.12 on 2026-04-08 04:19

import alignment.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0002_initial'),
        ('projects', '0003_repair_projectinvite_last_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stored_file', models.FileField(max_length=500, upload_to=alignment.models.stream_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=24)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_char_count', models.PositiveIntegerField(default=0)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('extraction_error', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='alignment.streampost')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_attachments', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='alignment_s_project_7d5338_idx'), models.Index(fields=['post', 'created_at'], name='alignment_s_post_id_7c0c6f_idx')],
            },
        ),
    ]
