# Generated by Django 5.2.12 on 2026-04-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0003_streamattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampost',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='streampost',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=16),
        ),
    ]
