# Generated by Django 5.2.12 on 2026-04-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0003_blocker_related_document_decision_related_document_and_more'),
        ('specs', '0004_alter_auditevent_event_type_concernrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampost',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='specs.projectconcern'),
        ),
    ]
