# Generated by Django 5.2.12 on 2026-03-25 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('prd', 'Product Requirements'), ('tech_spec', 'Technical Spec'), ('tasks', 'Task Breakdown'), ('agent', 'Coding Agent Prompt')], max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('expired', 'Expired'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField(blank=True)),
                ('share_enabled', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_exports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
