# Generated by Django 5.2.12 on 2026-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportartifact',
            name='format',
            field=models.CharField(choices=[('prd', 'Product Requirements'), ('tech_spec', 'Technical Spec'), ('tasks', 'Task Breakdown'), ('agent', 'Coding Agent Prompt'), ('uiux_agent', 'UI/UX Agent Prompt')], max_length=24),
        ),
    ]
